@startuml project2
Proxy "1" o-- "1" Cache
Cache "1" o-- "0..n" CacheFile
CacheFile "1" o-- "1" CacheFileVersion
OpenFile "0..n" -- "1" CacheFileVersion

Proxy "1" o-- "0..n" FileHandler
FileHandler "1" o-- "1" FDTable
FDTable "1" o-- "0..n" OpenFile

Proxy "0..n" -- "1" ServerOperations

interface ServerOperations{}
Server --|> ServerOperations
Server "1" -- "1" ServerTempFDTable
ServerTempFDTable "1" o-- "0..n" ServerTempFile
Server "1" -- "1" ServerFileTable
ServerFileTable "1" o-- "0..n" ServerFile
ServerTempFile "0..n" -- "1" ServerFile
@enduml
